"""profiles, cover photos and helpful answers

Revision ID: 16801f144026
Revises: 4089faaa3713
Create Date: 2026-10-06 12:03:47.764163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16801f144026'
down_revision = '4089faaa3713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('helpful_comment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_posts_helpful_comment', 'comments', ['helpful_comment_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('university', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('course', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('intake', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('intake')
        batch_op.drop_column('course')
        batch_op.drop_column('university')
        batch_op.drop_column('cover_url')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_helpful_comment', type_='foreignkey')
        batch_op.drop_column('helpful_comment_id')

    # ### end Alembic commands ###
