"""tymai sources on chat and ai messages

Revision ID: 27171b8a423a
Revises: 16801f144026
Create Date: 2026-10-06 12:42:13.987591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27171b8a423a'
down_revision = '16801f144026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sources', sa.JSON(), nullable=True))

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sources', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('sources')

    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_column('sources')

    # ### end Alembic commands ###
