"""photo id only age check

Revision ID: 4089faaa3713
Revises: 860cc57e90a4
Create Date: 2026-10-06 11:46:06.676557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4089faaa3713'
down_revision = '860cc57e90a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity_verifications', schema=None) as batch_op:
        batch_op.drop_column('id_face')
        batch_op.drop_column('face_score')
        batch_op.drop_column('selfie_key')
        batch_op.drop_column('attempts')
        batch_op.drop_column('document_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('selfie_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('face_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_face', postgresql.BYTEA(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
