"""identity verification and email codes

Revision ID: 70f7fda087b2
Revises: 074a1fc854af
Create Date: 2026-10-06 10:01:37.830824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70f7fda087b2'
down_revision = '074a1fc854af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_verifications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'review', 'verified', 'rejected', name='verification_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('document_type', sa.Enum('passport', 'driving_licence', 'national_id', name='document_type', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('dob_source', sa.Enum('mrz', 'label', 'date', name='dob_source', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('id_face', sa.LargeBinary(), nullable=True),
    sa.Column('document_key', sa.String(length=255), nullable=True),
    sa.Column('selfie_key', sa.String(length=255), nullable=True),
    sa.Column('face_score', sa.Float(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('selfie_verifications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_code_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('email_code_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('email_code_expires_at')
        batch_op.drop_column('email_code_hash')

    op.create_table('selfie_verifications',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('storage_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('reviewed_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])", name=op.f('selfie_status')),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('selfie_verifications_reviewed_by_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('selfie_verifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('selfie_verifications_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('selfie_verifications_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('identity_verifications')
    # ### end Alembic commands ###
