"""mentor booking payments and reviews

Revision ID: 860cc57e90a4
Revises: 70f7fda087b2
Create Date: 2026-10-06 10:38:05.812800

"""
from alembic import op
import sqlalchemy as sa

OLD_STATUSES = "'pending_payment', 'confirmed', 'cancelled', 'completed'"
NEW_STATUSES = OLD_STATUSES + ", 'expired'"


# revision identifiers, used by Alembic.
revision = '860cc57e90a4'
down_revision = '70f7fda087b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_reviews',
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_reviews_rating'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    with op.batch_alter_table('availability_slots', schema=None) as batch_op:
        batch_op.drop_column('is_booked')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('student_timezone', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('note', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('bookings_slot_id_key'), type_='unique')
        batch_op.create_index('uq_bookings_active_slot', ['slot_id'], unique=True, postgresql_where=sa.text("status IN ('pending_payment', 'confirmed')"))
    # A payment hold that runs out becomes 'expired'
    op.drop_constraint('booking_status', 'bookings', type_='check')
    op.create_check_constraint('booking_status', 'bookings', f"status IN ({NEW_STATUSES})")

    with op.batch_alter_table('mentor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topics', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('languages', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), nullable=False, server_default='Europe/London'))
        batch_op.add_column(sa.Column('weekly_hours', sa.JSON(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_refund_id', sa.String(length=64), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar_key', new_column_name='avatar_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar_url', new_column_name='avatar_key')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('razorpay_refund_id')

    with op.batch_alter_table('mentor_profiles', schema=None) as batch_op:
        batch_op.drop_column('weekly_hours')
        batch_op.drop_column('timezone')
        batch_op.drop_column('languages')
        batch_op.drop_column('topics')

    op.execute("UPDATE bookings SET status = 'cancelled' WHERE status = 'expired'")
    op.drop_constraint('booking_status', 'bookings', type_='check')
    op.create_check_constraint('booking_status', 'bookings', f"status IN ({OLD_STATUSES})")
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index('uq_bookings_active_slot', postgresql_where=sa.text("status IN ('pending_payment', 'confirmed')"))
        batch_op.create_unique_constraint(batch_op.f('bookings_slot_id_key'), ['slot_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('note')
        batch_op.drop_column('hold_expires_at')
        batch_op.drop_column('student_timezone')
        batch_op.drop_column('topic')

    with op.batch_alter_table('availability_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_booked', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.false()))

    op.drop_table('mentor_reviews')
    # ### end Alembic commands ###
