"""mentor applications

Revision ID: a419daf0a51a
Revises: 27171b8a423a
Create Date: 2026-10-06 12:52:13.755694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a419daf0a51a'
down_revision = '27171b8a423a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_applications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='mentor_application_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('university', sa.String(length=120), nullable=False),
    sa.Column('course', sa.String(length=120), nullable=False),
    sa.Column('graduation_year', sa.SmallInteger(), nullable=False),
    sa.Column('graduated', sa.Boolean(), nullable=False),
    sa.Column('headline', sa.String(length=160), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('experience', sa.String(length=255), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('session_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('weekly_hours', sa.JSON(), nullable=False),
    sa.Column('cv_key', sa.String(length=255), nullable=False),
    sa.Column('proof_key', sa.String(length=255), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentor_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentor_applications_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentor_applications_user_id'))

    op.drop_table('mentor_applications')
    # ### end Alembic commands ###
